id: I0285577C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T19:21:28+00:00'
last_modified: '2022-06-07T17:59:00.659360+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG01616
  title: རྒྱུད་སྡེ་ལྔ་གཙོ་བསྡུས་ཀྱི་བསྙེན་ཡིག་ཟབ་དོན་སྙིང་པོ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    D51C:
      image_group_id: I00KG02870
      title: ''
      total_pages: 22
      order: 1
      base_file: D51C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
