id: P003158
initial_creation_type: ocr
source_metadata:
  id: bdr:W00KG01616
  title: རྒྱུད་སྡེ་ལྔ་གཙོ་བསྡུས་ཀྱི་བསྙེན་ཡིག་ཟབ་དོན་སྙིང་པོ
  author: ''
  volumes:
    6c803779bd364ad6b951b028b2deef3d:
      image_group_id: I00KG02870
      title: ''
      volume_number: 1
      total_pages: 22
      base_file: v001.txt
